### ISSUE TITLE
credential events are not been stored by following module

### ISSUE THREAD

**Issue by itsdivyanshjain** [OWASP/Python-Honeypot#216]
#### module which are not storing credentials 
- http/basic_auth_weak_password/
- ssh/weak_password

While using module `http/basic_auth_strong_password/` which works completely fine and storing credential events while above mentioned modules credential events are not stored.

**Comment by ChakshuGupta** [comment]
Hi,

This is by design. The weak password modules are used to monitor hacker activities like what commands does the hacker perform after getting logged in easily. The strong password modules are used to monitor what does hacker provides as username/passwords to get into the system

**Comment by itsdivyanshjain** [comment]
Thanks for commenting, I misinterpreted the wiki guidelines.
