### ISSUE TITLE
Error while using ssh/strong_password module

### ISSUE THREAD

**Issue by itsdivyanshjain** [OWASP/Python-Honeypot#217]
#### Error
while using a module named ssh/strong_password i got an error paramiko return non-zero code and docker image not found (mentioned in image).

p.s: All other modules are working properly.

cmd: `python ohp.py -m ssh/strong_password` (as root user)

![ssh](https://user-images.githubusercontent.com/45870070/104812686-fd35d880-5829-11eb-915d-0cb95bfdb33a.png)

**Comment by dhirensr** [comment]
Hello @itsdivyanshjain ,
It seems there is a problem with this module. did you already have a look into that ?

**Comment by itsdivyanshjain** [comment]
Hi @dhirensr, I look into that and try to install different packages (for testing) and that probably worked, but when I try to install paramiko package it shows again same error. I have less idea about what causing an error.

**Comment by dhirensr** [comment]
@itsdivyanshjain  : I'll work on this issue and send a PR this week then :smile:

**Comment by Ali-Razmjoo** [comment]
thanks for reporting this, in order to not face this issue, we will add versioning in our dependencies in the modules as well, this issue should be resolve by #223 please test and let us know if you facing this issue again.
