### ISSUE TITLE
bug in module http/basic_auth_strong_password

### ISSUE THREAD

**Issue by mdomina** [OWASP/Python-Honeypot#241]
when the module http/basic_auth_strong_password registers the credentials in the database it writes the date wrong and this generates an error when the APIs are called.
HTTP
{ "_id" : ObjectId("602311d500a1577e5e2fd86b"), "ip" : "192.168.1.3", "module_name" : "http/basic_auth_strong_password", "date" : "[09/Feb/2021:22:51:01 +0000]", "username" : "test", "password" : "tesrrere", "machine_name" : "stockholm_server_1", "country" : "-" }
SSH
{ "_id" : ObjectId("602312da00a1577e5e308f34"), "ip" : "192.168.1.3", "module_name" : "ssh/strong_password", "date" : "2021-02-09 22:55:22", "username" : "test", "password" : "erer", "machine_name" : "stockholm_server_1", "country" : "-" }

**Comment by mdomina** [comment]
I solved.
edit file modules/http/basic_auth_strong_password/ __ init__.py 

Row 4
Before: 
import time

After:
import time, datetime

Row 40
Before:
time_of_insertion = data_json["time"]

After:
date_log = data_json["time"]
date = date_log[1:12]
time_of_insertion = date + ' ' + date_log[13:21]

**Comment by dhirensr** [comment]
@mdomina : can you send a PR for this? it's very difficult to understand the changes in plaintext.

**Comment by mdomina** [comment]
> 
> 
> @mdomina : can you send a PR for this? it's very difficult to understand the changes in plaintext.

https://github.com/OWASP/Python-Honeypot/pull/246

**Comment by Ali-Razmjoo** [comment]
let me know if you still facing the issue.
