### ISSUE TITLE
requirements-apt-get issue

### ISSUE THREAD

**Issue by itsdivyanshjain** [OWASP/Python-Honeypot#245]
As, we have added requirements file for apt package manager, but now when the packages get updated old package version not available which leads to fails to build an image. Currently this issue affecting the module `ssh/strong_password`.

I think we need to give priority to setup Dependbot for it.

**Comment by dhirensr** [comment]
@itsdivyanshjain : I didn't really understood the issue. If everything in requirements file was tested and package numbers were correct for the docker image of ubuntu:20.04, then why would the package suddenly become unavailable?
could you explain more briefly?

**Comment by itsdivyanshjain** [comment]
Hello @dhirensr,

So, when packages get updated like in our case for module `ssh/strong_password` the package `libssl-dev=1.1.1f-1ubuntu2.1` updated to   `libssl-dev=1.1.1f-1ubuntu2.2`. Now our old package version is no longer available in apt-cache and we can install or rollback only if a version is available in apt-cache of that package.

cmd: `apt-cache showpkg package-name`

P.S: I don't know why the apt package manager is not having an old version of it. I am trying to find out the reason behind this,but If you find out let me know about it.

**Comment by Ali-Razmjoo** [comment]
this is fixed now but it gonna have errors in feature when it's updated again, I am open to feedbacks if you know how to fix this?
