### ISSUE TITLE
Log explorer export doesn't exports all the records

### ISSUE THREAD

**Issue by dhirensr** [OWASP/Python-Honeypot#297]
Hello @Ali-Razmjoo ,
In the log explorer UI if we filter the data, the table shows multiple pages in output, but when I click on export CSV,EXCEL ,it only gives me records present on that page and not from all the pages.

Is that behaviour expected or is it a bug and rather it should have exported all the data satisfying the filter in the UI?

**Comment by Ali-Razmjoo** [comment]
Good point, maybe base on time and date we need to export all?

**Comment by spiderxm** [comment]
@Ali-Razmjoo @dhirensr . This happens due to the use of pipelining as records are fetched in batch of 100.
When user clicks to export we can fetch all the matching records in one go. Convert them to matching format and then download.

**Comment by dhirensr** [comment]
@spiderxm : thank you for checking into that. I think based on time and date filter we need to export all records in csv/excel/json and not only the first page of the table.
can you fix that?

**Comment by spiderxm** [comment]
Yes, on it
