### ISSUE TITLE
problem with terminable thread 

### ISSUE THREAD

**Issue by DTnavy** [OWASP/Python-Honeypot#319]
raceback (most recent call last):
  File "/home/user/Desktop/test/Python-Honeypot/ohp.py", line 5, in <module>
    from core.load import load_honeypot_engine
  File "/home/user/Desktop/test/Python-Honeypot/core/load.py", line 11, in <module>
    from terminable_thread import Thread, threading
ModuleNotFoundError: No module named 'terminable_thread'

i got this when i want to run the ohp.py file using python3 can i know why it cannot find terminable_thread

**Comment by spiderxm** [comment]
@DTnavy have you installed all the requirements present in `requirements.txt` file

**Comment by Ali-Razmjoo** [comment]
@DTnavy  please feel free to reopen this later again if you face the issue after installing requirements.

**Comment by K0zero** [comment]
well， i have installed the requirements and i restarted my vm machine but the error still had
