### ISSUE TITLE
a question of changing protocol

### ISSUE THREAD

**Issue by K0zero** [OWASP/Python-Honeypot#344]
I'm considering making a honeynet system for ICS, and I think the project you've done is great.
so I'd like to ask if honeypots support changing protocols for communicating with each other,  
such like modbus( a Industrial control protocol )
and if honeypots can emulate a virtual industrial control PLC
thanks

**Comment by Ali-Razmjoo** [comment]
Hi,

sorry for my late reply, I implemented the protocol myself manually and created the responses, if you have any guidelines on how to create modbus server, I can help you to create a new module for that.

Bests, Ali.

**Comment by K0zero** [comment]
well, if this project can use customized modules with docker,
i can make a modbus sercver dockerfile from another project which called conpot.
