### ISSUE TITLE
problem with terminable thread

### ISSUE THREAD

**Issue by K0zero** [OWASP/Python-Honeypot#345]
I have installed all the requirements packeges but
it noticed
pip3 install -r requirements.txt ---> terminable-thread==0.7.1  not installed!
even i restarted machine the problem still have

**Comment by ChakshuGupta** [comment]
Could you provide the exact commands executed, in the exact order, that gave this error?
Also the environment, i.e. the OS, python version, etc.

**Comment by K0zero** [comment]
well, i have solved the problem but i forgot how i solved it, thanks for your attention! 
:-)
